FROM openjdk:17
EXPOSE 6001
ADD target/ForexServiceNamingEurekaServer-0.0.1-SNAPSHOT.jar ForexServiceNamingEurekaServer-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "ForexServiceNamingEurekaServer-0.0.1-SNAPSHOT.jar"]